const BOOKING_CONTENT = Object.freeze({
  it: Object.freeze({
    eyebrow: "CONCEDITI UN MOMENTO DI RELAX",
    heading: "Prenota un appuntamento",
    intro:
      "Seleziona il trattamento, poi scegli la data e l’orario che preferisci.",
    selectDate: "Seleziona data*",
    selectTime: "Seleziona orario*",
    loadingTimes: "Caricamento orari disponibili...",
    unavailable: "Il servizio non è disponibile. Riprova tra poco.",
    retry: "Riprova",
    noTimes: "Nessun orario disponibile per questa data",
    treatment: "Trattamento*",
    selectTreatment: "Seleziona trattamento",
    duration: "Durata del trattamento*",
    optionCount: (count) => ` (${count} opzioni)`,
    selectDuration: "Seleziona durata",
    minutes: (value) => `${value} minuti`,
    showLess: "Mostra meno",
    showMore: (count) => `Mostra più (${count} altri)`,
    note: "Note",
    notePlaceholder: "Note aggiuntive (opzionale)",
    name: "Nome e Cognome*",
    namePlaceholder: "Es. Mario Rossi",
    email: "Email*",
    phone: "Numero di telefono*",
    securityRequired: "Completa la verifica di sicurezza per continuare.",
    securityUnavailable:
      "La verifica non è disponibile. Ricarica la pagina e riprova.",
    bookingLoading: "Prenotazione in corso...",
    bookingSuccess: "Appuntamento prenotato con successo!",
    submit: "Prenota Appuntamento",
    required: "I campi contrassegnati con * sono obbligatori",
    missingPrefix: "Compila tutti i campi obbligatori prima di prenotare:",
    missingFields: Object.freeze({
      appointmentType: "Trattamento",
      date: "Data",
      duration: "Durata del trattamento",
      email: "Email",
      name: "Nome e Cognome",
      number: "Numero di telefono",
      timeSlot: "Orario",
    }),
    invalidCatalog:
      "Il trattamento selezionato non è disponibile. Ricarica la pagina e riprova.",
    confirmation: "L’appuntamento è stato prenotato",
    closeConfirmation: "Chiudi conferma prenotazione",
  }),
  en: Object.freeze({
    eyebrow: "TAKE TIME FOR YOURSELF",
    heading: "Book an appointment",
    intro: "Choose a treatment, then select your preferred date and time.",
    selectDate: "Select a date*",
    selectTime: "Select a time*",
    loadingTimes: "Loading available times...",
    unavailable: "The service is unavailable. Please try again shortly.",
    retry: "Try again",
    noTimes: "No times are available on this date",
    treatment: "Treatment*",
    selectTreatment: "Select a treatment",
    duration: "Treatment duration*",
    optionCount: (count) => ` (${count} options)`,
    selectDuration: "Select a duration",
    minutes: (value) => `${value} minutes`,
    showLess: "Show fewer times",
    showMore: (count) => `Show more (${count} more)`,
    note: "Notes",
    notePlaceholder: "Additional notes (optional)",
    name: "Full name*",
    namePlaceholder: "e.g. Jane Smith",
    email: "Email*",
    phone: "Phone number*",
    securityRequired: "Complete the security check to continue.",
    securityUnavailable:
      "The security check is unavailable. Reload the page and try again.",
    bookingLoading: "Booking your appointment...",
    bookingSuccess: "Your appointment has been booked!",
    submit: "Book appointment",
    required: "Fields marked with * are required",
    missingPrefix: "Complete all required fields before booking:",
    missingFields: Object.freeze({
      appointmentType: "Treatment",
      date: "Date",
      duration: "Treatment duration",
      email: "Email",
      name: "Full name",
      number: "Phone number",
      timeSlot: "Time",
    }),
    invalidCatalog:
      "The selected treatment is unavailable. Reload the page and try again.",
    confirmation: "Your appointment has been booked",
    closeConfirmation: "Close booking confirmation",
  }),
});

export function bookingContent(locale = "it") {
  return locale === "en" ? BOOKING_CONTENT.en : BOOKING_CONTENT.it;
}
