export const RESOURCE_ID = "40000000-0000-4000-8000-000000000001";
const SECOND_RESOURCE_ID = "60000000-0000-4000-8000-000000000001";

export const OWNER_ROUTE_COMMAND_CASES = [
  {
    commandName: "createAppointment",
    path: "/api/admin/appointments",
    operation: "owner_create_appointment",
    status: 201,
    code: "APPOINTMENT_CREATED",
    body: {
      date: "2035-01-02",
      startMinutes: 600,
      serviceId: "massaggio-relax",
      variantId: "massaggio-relax-60",
      clientName: " Cliente Test ",
      clientEmail: " CLIENT@example.test ",
      clientPhone: "+39 333 123 4567",
    },
    normalizedBody: {
      date: "2035-01-02",
      startMinutes: 600,
      serviceId: "massaggio-relax",
      variantId: "massaggio-relax-60",
      clientName: "Cliente Test",
      clientEmail: "client@example.test",
      clientPhone: "+393331234567",
      clientNote: null,
    },
  },
  {
    commandName: "createBlock",
    path: "/api/admin/blocks",
    operation: "owner_create_block",
    status: 201,
    code: "BLOCK_CREATED",
    body: {
      date: "2035-01-02",
      startMinutes: 720,
      durationMinutes: 30,
      internalNote: " Pausa ",
    },
    normalizedBody: {
      date: "2035-01-02",
      startMinutes: 720,
      durationMinutes: 30,
      bufferMinutes: 0,
      internalNote: "Pausa",
    },
  },
  {
    commandName: "updateAppointment",
    path: "/api/admin/appointments/details",
    operation: "owner_update_appointment_details",
    status: 200,
    code: "APPOINTMENT_DETAILS_UPDATED",
    body: {
      entryId: SECOND_RESOURCE_ID.toUpperCase(),
      expectedVersion: 2,
      clientName: " Cliente Aggiornato ",
      clientEmail: " UPDATED@example.test ",
      clientPhone: "+39 333 765 4321",
      clientNote: " Nota cliente ",
      internalNote: " Nota interna ",
    },
    normalizedBody: {
      entryId: SECOND_RESOURCE_ID,
      expectedVersion: 2,
      clientName: "Cliente Aggiornato",
      clientEmail: "updated@example.test",
      clientPhone: "+393337654321",
      clientNote: "Nota cliente",
      internalNote: "Nota interna",
    },
  },
  {
    commandName: "updateBlock",
    path: "/api/admin/blocks/details",
    operation: "owner_update_block_details",
    status: 200,
    code: "BLOCK_DETAILS_UPDATED",
    body: {
      entryId: SECOND_RESOURCE_ID.toUpperCase(),
      expectedVersion: 3,
      internalNote: " Pausa aggiornata ",
    },
    normalizedBody: {
      entryId: SECOND_RESOURCE_ID,
      expectedVersion: 3,
      internalNote: "Pausa aggiornata",
    },
  },
  {
    commandName: "rescheduleAppointment",
    path: "/api/admin/appointments/reschedule",
    operation: "owner_reschedule_appointment",
    status: 200,
    code: "APPOINTMENT_RESCHEDULED",
    body: {
      entryId: SECOND_RESOURCE_ID.toUpperCase(),
      expectedVersion: 4,
      date: "2035-01-03",
      startMinutes: 660,
      serviceId: " manicure ",
      variantId: " manicure-30 ",
    },
    normalizedBody: {
      entryId: SECOND_RESOURCE_ID,
      expectedVersion: 4,
      date: "2035-01-03",
      startMinutes: 660,
      serviceId: "manicure",
      variantId: "manicure-30",
    },
  },
  {
    commandName: "rescheduleBlock",
    path: "/api/admin/blocks/reschedule",
    operation: "owner_reschedule_block",
    status: 200,
    code: "BLOCK_RESCHEDULED",
    body: {
      entryId: SECOND_RESOURCE_ID.toUpperCase(),
      expectedVersion: 5,
      date: "2035-01-03",
      startMinutes: 780,
      durationMinutes: 45,
    },
    normalizedBody: {
      entryId: SECOND_RESOURCE_ID,
      expectedVersion: 5,
      date: "2035-01-03",
      startMinutes: 780,
      durationMinutes: 45,
      bufferMinutes: 0,
    },
  },
  {
    commandName: "setAppointmentStatus",
    path: "/api/admin/appointments/status",
    operation: "owner_set_appointment_status",
    status: 200,
    code: "APPOINTMENT_STATUS_UPDATED",
    body: {
      entryId: SECOND_RESOURCE_ID.toUpperCase(),
      expectedVersion: 6,
      status: "completed",
    },
    normalizedBody: {
      entryId: SECOND_RESOURCE_ID,
      expectedVersion: 6,
      status: "completed",
    },
  },
  {
    commandName: "cancelScheduleEntry",
    path: "/api/admin/schedule/cancel",
    operation: "owner_cancel_schedule_entry",
    status: 200,
    code: "SCHEDULE_ENTRY_CANCELLED",
    body: {
      entryId: RESOURCE_ID,
      expectedVersion: 2,
      reason: " Richiesta cliente ",
    },
    normalizedBody: {
      entryId: RESOURCE_ID,
      expectedVersion: 2,
      reason: "Richiesta cliente",
    },
  },
  {
    commandName: "createVacation",
    path: "/api/admin/vacations",
    operation: "owner_create_vacation",
    status: 201,
    code: "VACATION_CREATED",
    body: {
      startDate: "2035-02-01",
      endDate: "2035-02-05",
      reason: " Ferie ",
    },
    normalizedBody: {
      startDate: "2035-02-01",
      endDate: "2035-02-05",
      reason: "Ferie",
    },
  },
  {
    commandName: "cancelVacation",
    path: "/api/admin/vacations/cancel",
    operation: "owner_cancel_vacation",
    status: 200,
    code: "VACATION_CANCELLED",
    body: { vacationId: RESOURCE_ID, expectedVersion: 3 },
    normalizedBody: { vacationId: RESOURCE_ID, expectedVersion: 3 },
  },
] as const;
