-- Generated from lib/domain/catalog/manifest.ts.
-- Manifest SHA-256: 74f97f4fcae84e19158bd8fba9d6386c446539feef0c4998d47c760d5c1c34b7
begin;

set local lock_timeout = '5s';
set local statement_timeout = '30s';

insert into gioia_private.service_variants (
  id,
  service_id,
  display_name_it,
  sort_order,
  duration_minutes,
  buffer_minutes,
  price_cents,
  currency,
  active
)
values
  ('applicazione-di-smalto-semipermanente-60-min', 'applicazione-di-smalto-semipermanente', 'Applicazione di smalto semipermanente', 0, 60, 5, null, null, true),
  ('applicazione-di-smalto-semipermanente-rinforzato-90-min', 'applicazione-di-smalto-semipermanente-rinforzato', 'Applicazione di smalto semipermanente rinforzato', 0, 90, 5, null, null, true),
  ('applicazione-smalto-classico-45-min', 'applicazione-smalto-classico', 'Applicazione smalto classico', 0, 45, 5, null, null, true),
  ('architettura-sopracciglia-40-min', 'architettura-sopracciglia', 'Architettura sopracciglia', 0, 40, 5, null, null, true),
  ('ascelle-25-min', 'ascelle', 'Ascelle', 0, 25, 5, null, null, true),
  ('attivatore-splendore-immediato-60-min', 'attivatore-splendore-immediato', 'Attivatore splendore immediato', 0, 60, 5, null, null, true),
  ('baffetti-15-min', 'baffetti', 'Baffetti', 0, 15, 5, null, null, true),
  ('baffetti-e-sopracciglia-10-min', 'baffetti-e-sopracciglia', 'Baffetti e sopracciglia', 0, 10, 10, null, null, true),
  ('bendaggio-specifico-60-min', 'bendaggio-specifico', 'Bendaggio specifico', 0, 60, 15, null, null, true),
  ('body-brushing-mineralizzante-50-min', 'body-brushing-mineralizzante', 'Body brushing 50 minuti', 0, 50, 15, null, null, true),
  ('body-brushing-mineralizzante-90-min', 'body-brushing-mineralizzante', 'Body brushing 90 minuti', 1, 90, 15, null, null, true),
  ('braccia-15-min', 'braccia', 'Braccia', 0, 15, 5, null, null, true),
  ('calcoterapia-decongestionante-rassodante-60-min', 'calcoterapia-decongestionante-rassodante', 'Calcoterapia decongestionante-rassodante', 0, 60, 15, null, null, true),
  ('combinazione-laminazione-ciglia-e-sopracciglia-70-min', 'combinazione-laminazione-ciglia-e-sopracciglia', 'Combinazione laminazione ciglia e sopracciglia', 0, 70, 5, null, null, true),
  ('consulenza-endermologie-60-min', 'consulenza-endermologie', 'Consulenza endermologie®', 0, 60, 5, null, null, true),
  ('consulenza-laser-30-min', 'consulenza-laser', 'Consulenza laser', 0, 30, 5, null, null, true),
  ('copertura-gel-delle-unghie-naturali-90-min', 'copertura-gel-delle-unghie-naturali', 'Copertura gel delle unghie naturali', 0, 90, 5, null, null, true),
  ('corso-individuale-di-make-up-base-120-min', 'corso-individuale-di-make-up-base', 'Corso individuale di make-up base', 0, 120, 5, null, null, true),
  ('detox-40-min', 'detox', 'Detox', 0, 40, 5, null, null, true),
  ('elite-active-60-min', 'elite-active', 'Elite active', 0, 60, 15, null, null, true),
  ('epilazione-con-filo-arabo-delle-sopracciglia-15-min', 'epilazione-con-filo-arabo-delle-sopracciglia', 'Epilazione con filo arabo delle sopracciglia', 0, 15, 5, null, null, true),
  ('gamba-intera-60-min', 'gamba-intera', 'Gamba intera', 0, 60, 5, null, null, true),
  ('gamba-intera-uomo-35-min', 'gamba-intera-uomo', 'Gamba intera uomo', 0, 35, 15, null, null, true),
  ('glutei-30-min', 'glutei', 'Glutei', 0, 30, 5, null, null, true),
  ('grow-up-sopracciglia-30-min', 'grow-up-sopracciglia', 'Grow up sopracciglia', 0, 30, 5, null, null, true),
  ('inguine-parziale-20-min', 'inguine-parziale', 'Inguine parziale', 0, 20, 5, null, null, true),
  ('inguine-totale-30-min', 'inguine-totale', 'Inguine totale', 0, 30, 5, null, null, true),
  ('laminazione-ciglia-60-min', 'laminazione-ciglia', 'Laminazione ciglia', 0, 60, 5, null, null, true),
  ('laminazione-sopracciglia-60-min', 'laminazione-sopracciglia', 'Laminazione sopracciglia', 0, 60, 5, null, null, true),
  ('manicure-30-min', 'manicure', 'Manicure', 0, 30, 5, null, null, true),
  ('manicure-giapponese-45-min', 'manicure-giapponese', 'Manicure Giapponese', 0, 45, 5, null, null, true),
  ('manicure-spa-50-min', 'manicure-spa', 'Manicure SPA', 0, 50, 5, null, null, true),
  ('massaggio-con-pindasweda-30-min', 'massaggio-con-pindasweda', 'Massaggio Pindasweda 30 minuti', 0, 30, 15, null, null, true),
  ('massaggio-con-pindasweda-50-min', 'massaggio-con-pindasweda', 'Massaggio Pindasweda 50 minuti', 1, 50, 15, null, null, true),
  ('massaggio-corpo-al-cioccolato-45-min', 'massaggio-corpo-al-cioccolato', 'Massaggio corpo al cioccolato', 0, 45, 15, null, null, true),
  ('massaggio-corpo-personalizzato-30-min', 'massaggio-corpo-personalizzato', 'Massaggio 30 minuti', 0, 30, 15, null, null, true),
  ('massaggio-corpo-personalizzato-60-min', 'massaggio-corpo-personalizzato', 'Massaggio 60 minuti', 1, 60, 15, null, null, true),
  ('massaggio-viso-personalizzato-30-min', 'massaggio-viso-personalizzato', 'Massaggio viso personalizzato', 0, 30, 5, null, null, true),
  ('mezza-gamba-45-min', 'mezza-gamba', 'Mezza gamba', 0, 45, 5, null, null, true),
  ('nanoblading-grow-brows-180-min', 'nanoblading-grow-brows', 'Nanoblading grow brows', 0, 180, 25, null, null, true),
  ('nemesis-60-min', 'nemesis', 'Nemesis', 0, 60, 15, null, null, true),
  ('ossigeno-dermo-infusione-60-min', 'ossigeno-dermo-infusione', 'Ossigeno dermo infusione', 0, 60, 15, null, null, true),
  ('pedicure-60-min', 'pedicure', 'Pedicure', 0, 60, 5, null, null, true),
  ('pedicure-spa-60-min', 'pedicure-spa', 'Pedicure SPA', 0, 60, 15, null, null, true),
  ('pedicure-berbero-75-min', 'pedicure-berbero', 'Pedicure berbero', 0, 75, 10, null, null, true),
  ('pedicure-completa-con-cheratolitico-60-min', 'pedicure-completa-con-cheratolitico', 'Pedicure completa con cheratolitico', 0, 60, 30, null, null, true),
  ('pedicure-polinesiano-75-min', 'pedicure-polinesiano', 'Pedicure polinesiano', 0, 75, 10, null, null, true),
  ('pedicure-siberiano-75-min', 'pedicure-siberiano', 'Pedicure siberiano', 0, 75, 10, null, null, true),
  ('petto-30-min', 'petto', 'Petto', 0, 30, 5, null, null, true),
  ('pressoterapia-30-min', 'pressoterapia', 'Pressoterapia 30 minuti', 0, 30, 15, null, null, true),
  ('pressoterapia-45-min', 'pressoterapia', 'Pressoterapia 45 minuti', 1, 45, 15, null, null, true),
  ('pulizia-del-viso-con-spatola-ad-ultrasuoni-60-min', 'pulizia-del-viso-con-spatola-ad-ultrasuoni', 'Pulizia del viso con spatola ad ultrasuoni', 0, 60, 15, null, null, true),
  ('pulizia-del-viso-ultrasuoni-e-mandelico-60-min', 'pulizia-del-viso-ultrasuoni-e-mandelico', 'Pulizia del viso ultrasuoni e mandelico', 0, 60, 15, null, null, true),
  ('rituale-amazzonia-50-min', 'rituale-amazzonia', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-amazzonia-60-min', 'rituale-amazzonia', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-amazzonia-90-min', 'rituale-amazzonia', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-bora-bora-50-min', 'rituale-bora-bora', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-bora-bora-60-min', 'rituale-bora-bora', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-bora-bora-90-min', 'rituale-bora-bora', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-coccole-di-cotone-50-min', 'rituale-coccole-di-cotone', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-coccole-di-cotone-60-min', 'rituale-coccole-di-cotone', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-coccole-di-cotone-90-min', 'rituale-coccole-di-cotone', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-cute-50-min', 'rituale-cute', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-cute-60-min', 'rituale-cute', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-cute-90-min', 'rituale-cute', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-himalaya-50-min', 'rituale-himalaya', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-himalaya-60-min', 'rituale-himalaya', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-himalaya-90-min', 'rituale-himalaya', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-india-50-min', 'rituale-india', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-india-60-min', 'rituale-india', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-india-90-min', 'rituale-india', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-kleopatra-50-min', 'rituale-kleopatra', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-kleopatra-60-min', 'rituale-kleopatra', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-kleopatra-90-min', 'rituale-kleopatra', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-kyoto-50-min', 'rituale-kyoto', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-kyoto-60-min', 'rituale-kyoto', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-kyoto-90-min', 'rituale-kyoto', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-marrakech-50-min', 'rituale-marrakech', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-marrakech-60-min', 'rituale-marrakech', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-marrakech-90-min', 'rituale-marrakech', '90 minuti', 2, 90, 15, null, null, true),
  ('rituale-siberia-50-min', 'rituale-siberia', '50 minuti', 0, 50, 15, null, null, true),
  ('rituale-siberia-60-min', 'rituale-siberia', '60 minuti', 1, 60, 15, null, null, true),
  ('rituale-siberia-90-min', 'rituale-siberia', '90 minuti', 2, 90, 15, null, null, true),
  ('salagione-60-min', 'salagione', 'Salagione', 0, 60, 15, null, null, true),
  ('savonage-hammam-50-min', 'savonage-hammam', 'Savonage hammam 50 minuti', 0, 50, 15, null, null, true),
  ('savonage-hammam-90-min', 'savonage-hammam', 'Savonage hammam 90 minuti', 1, 90, 15, null, null, true),
  ('schiena-60-min', 'schiena', 'Schiena', 0, 60, 5, null, null, true),
  ('scrub-al-te-verde-50-min', 'scrub-al-te-verde', 'Scrub al tè verde 50 minuti', 0, 50, 15, null, null, true),
  ('scrub-al-te-verde-90-min', 'scrub-al-te-verde', 'Scrub al tè verde 90 minuti', 1, 90, 15, null, null, true),
  ('scrub-corpo-aromatico-30-min', 'scrub-corpo-aromatico', '30 minuti', 0, 30, 15, null, null, true),
  ('scrub-corpo-aromatico-60-min', 'scrub-corpo-aromatico', '60 minuti', 1, 60, 15, null, null, true),
  ('scrub-drenante-al-sale-integrale-50-min', 'scrub-drenante-al-sale-integrale', 'Scrub drenante 50 minuti', 0, 50, 15, null, null, true),
  ('scrub-drenante-al-sale-integrale-90-min', 'scrub-drenante-al-sale-integrale', 'Scrub drenante 90 minuti', 1, 90, 15, null, null, true),
  ('seduta-di-bagno-turco-60-min', 'seduta-di-bagno-turco', 'Seduta di Bagno Turco', 0, 60, 15, null, null, true),
  ('snellente-localizzato-cacao-e-calco-termico-75-min', 'snellente-localizzato-cacao-e-calco-termico', 'Snellente localizzato cacao e calco termico', 0, 75, 15, null, null, true),
  ('sopracciglia-15-min', 'sopracciglia', 'Sopracciglia', 0, 15, 5, null, null, true),
  ('thalassa-alga-gigante-90-min', 'thalassa-alga-gigante', 'Thalassa alga gigante', 0, 90, 15, null, null, true),
  ('trattamenti-viso-specifici-60-min', 'trattamenti-viso-specifici', 'Trattamenti viso specifici', 0, 60, 15, null, null, true),
  ('trattamento-artico-gambe-60-min', 'trattamento-artico-gambe', 'Trattamento artico gambe', 0, 60, 15, null, null, true),
  ('trattamento-minerale-al-limo-di-salina-60-min', 'trattamento-minerale-al-limo-di-salina', 'Trattamento minerale al limo di salina', 0, 60, 15, null, null, true),
  ('trattamento-viso-eterna-90-min', 'trattamento-viso-eterna', 'Trattamento viso Eterna', 0, 90, 15, null, null, true),
  ('trattamento-viso-fast-beauty-30-min', 'trattamento-viso-fast-beauty', 'Trattamento viso Fast Beauty', 0, 30, 15, null, null, true);

do $catalog_count$
begin
  if (select count(*) from gioia_private.service_variants) <> 102 then
    raise exception 'Unexpected service_variants row count';
  end if;
end
$catalog_count$;

commit;
