begin;
set local lock_timeout = '5s';
set local statement_timeout = '30s';
grant gioia_mutator to postgres;
grant gioia_migrator to postgres;
grant create on schema gioia_private to gioia_mutator;
grant create on schema gioia_private to gioia_migrator;
set local role gioia_migrator;
create function gioia_private.begin_legacy_migration_import( p_run_id uuid, p_source_project_ref text, p_source_manifest_sha256 bytea, p_expected_source_count smallint ) returns boolean language plpgsql volatile security definer set search_path = '' as $$ declare v_run gioia_private.migration_runs%rowtype;
begin if p_run_id is null or p_source_project_ref is null or pg_catalog.octet_length(p_source_project_ref) not between 6 and 255 or p_source_manifest_sha256 is null or pg_catalog.octet_length(p_source_manifest_sha256) <> 32 or p_expected_source_count not between 1 and 100 then raise sqlstate 'PT422' using message = 'MIGRATION_IMPORT_INVALID';
end if;
select run.* into v_run from gioia_private.migration_runs as run where run.id = p_run_id for update;
if found then if v_run.run_kind <> 'import' or v_run.source_project_ref <> p_source_project_ref or v_run.dry_run or v_run.source_manifest_sha256 <> p_source_manifest_sha256 or v_run.status not in ('running', 'completed') or (case when v_run.status = 'running' then (v_run.counts ->> 'expectedSource')::integer else (v_run.counts ->> 'source')::integer end) is distinct from p_expected_source_count then raise sqlstate 'PT409' using message = 'MIGRATION_RUN_MISMATCH';
end if;
return false;
end if;
insert into gioia_private.migration_runs ( id, run_kind, source_project_ref, dry_run, status, source_manifest_sha256, counts ) values ( p_run_id, 'import', p_source_project_ref, false, 'running', p_source_manifest_sha256, pg_catalog.jsonb_build_object('expectedSource', p_expected_source_count) );
return true;
end;
$$;
create function gioia_private.prepare_legacy_migration_import_record( p_run_id uuid, p_source_collection text, p_source_record_id text, p_source_record_sha256 bytea, p_disposition text, p_target_kind text, p_target_id uuid, p_target_record_sha256 bytea ) returns text language plpgsql volatile security definer set search_path = '' as $$ declare v_run gioia_private.migration_runs%rowtype;
v_existing gioia_private.migration_records%rowtype;
v_prior gioia_private.migration_records%rowtype;
v_expected integer;
v_count integer;
begin if p_source_collection not in ( 'customers', 'vacations', 'newsletter_subscribers' ) or p_source_record_id is null or pg_catalog.octet_length(p_source_record_id) not between 1 and 1500 or p_source_record_sha256 is null or pg_catalog.octet_length(p_source_record_sha256) <> 32 or p_disposition not in ('imported', 'quarantined') or ( p_disposition = 'imported' and ( p_target_kind not in ('schedule_entry', 'vacation', 'subscriber') or p_target_id is null or p_target_record_sha256 is null or pg_catalog.octet_length(p_target_record_sha256) <> 32 ) ) or ( p_disposition = 'quarantined' and ( p_target_kind is not null or p_target_id is not null or p_target_record_sha256 is not null ) ) then raise sqlstate 'PT422' using message = 'MIGRATION_RECORD_INVALID';
end if;
select run.* into v_run from gioia_private.migration_runs as run where run.id = p_run_id for update;
if not found or v_run.run_kind <> 'import' or v_run.dry_run or v_run.status not in ('running', 'completed') then raise sqlstate 'PT409' using message = 'MIGRATION_RUN_NOT_WRITABLE';
end if;
select record.* into v_existing from gioia_private.migration_records as record where record.run_id = p_run_id and record.source_collection = p_source_collection and record.source_record_id = p_source_record_id;
if found then if v_existing.source_record_sha256 <> p_source_record_sha256 then raise sqlstate 'PT409' using message = 'MIGRATION_SOURCE_CHECKSUM_CHANGED';
end if;
if v_existing.disposition <> p_disposition or v_existing.target_kind is distinct from p_target_kind or v_existing.target_id is distinct from p_target_id or v_existing.target_record_sha256 is distinct from p_target_record_sha256 then raise sqlstate 'PT409' using message = 'MIGRATION_RECORD_MISMATCH';
end if;
return 'same_run_replay';
end if;
if v_run.status = 'completed' then raise sqlstate 'PT409' using message = 'MIGRATION_RUN_COMPLETED';
end if;
if exists ( select 1 from gioia_private.migration_records as history where history.source_collection = p_source_collection and history.source_record_id = p_source_record_id and history.source_record_sha256 <> p_source_record_sha256 ) then raise sqlstate 'PT409' using message = 'MIGRATION_SOURCE_CHECKSUM_CHANGED';
end if;
select history.* into v_prior from gioia_private.migration_records as history where history.source_collection = p_source_collection and history.source_record_id = p_source_record_id order by history.recorded_at desc, history.run_id desc limit 1;
if found and ( v_prior.disposition <> p_disposition or v_prior.target_kind is distinct from p_target_kind or v_prior.target_id is distinct from p_target_id or v_prior.target_record_sha256 is distinct from p_target_record_sha256 ) then raise sqlstate 'PT409' using message = 'MIGRATION_RECORD_MISMATCH';
end if;
v_expected := (v_run.counts ->> 'expectedSource')::integer;
select pg_catalog.count(*)::integer into v_count from gioia_private.migration_records as record where record.run_id = p_run_id;
if v_expected is null or v_expected not between 1 and 100 or v_count >= v_expected or v_count >= 100 then raise sqlstate 'PT422' using message = 'MIGRATION_BATCH_LIMIT_EXCEEDED';
end if;
insert into gioia_private.migration_records ( run_id, source_collection, source_record_id, source_record_sha256, disposition, target_kind, target_id, target_record_sha256 ) values ( p_run_id, p_source_collection, p_source_record_id, p_source_record_sha256, p_disposition, p_target_kind, p_target_id, p_target_record_sha256 );
return case when v_prior.run_id is null then 'new' else 'prior_run_replay' end;
end;
$$;
reset role;
set local role gioia_mutator;
create function gioia_private.apply_legacy_schedule_import( p_run_id uuid, p_source_record_id text, p_source_record_sha256 bytea, p_target_record_sha256 bytea, p_target_id uuid, p_legacy_firestore_id text, p_kind text, p_status text, p_local_date date, p_start_minutes smallint, p_service_duration_minutes smallint, p_buffer_minutes smallint, p_service_id text, p_variant_id text, p_service_name_snapshot text, p_variant_name_snapshot text, p_price_cents_snapshot integer, p_currency_snapshot text, p_client_name text, p_client_email text, p_client_phone text, p_client_note text, p_internal_note text, p_cancelled_by text, p_cancelled_at timestamptz, p_cancellation_reason text, p_timestamp_provenance text, p_imported_at timestamptz, p_created_at timestamptz, p_updated_at timestamptz, p_version integer ) returns boolean language plpgsql volatile security definer set search_path = '' as $$ declare v_mode text;
begin if p_legacy_firestore_id is distinct from p_source_record_id then raise sqlstate 'PT422' using message = 'MIGRATION_LEGACY_ID_MISMATCH';
end if;
v_mode := gioia_private.prepare_legacy_migration_import_record( p_run_id, 'customers', p_source_record_id, p_source_record_sha256, 'imported', 'schedule_entry', p_target_id, p_target_record_sha256 );
if v_mode <> 'new' then if not exists ( select 1 from gioia_private.schedule_entries as entry where entry.id = p_target_id and entry.legacy_firestore_id = p_source_record_id and entry.source = 'migration' ) then raise sqlstate 'PT409' using message = 'MIGRATION_TARGET_MISSING';
end if;
return false;
end if;
insert into gioia_private.schedule_entries ( id, schema_version, kind, status, source, local_date, start_minutes, service_duration_minutes, buffer_minutes, service_id, variant_id, service_name_snapshot, variant_name_snapshot, price_cents_snapshot, currency_snapshot, client_name, client_email, client_phone, client_note, internal_note, created_by, legacy_firestore_id, timestamp_provenance, imported_at, cancelled_at, cancelled_by, cancellation_reason, version, created_at, updated_at ) values ( p_target_id, 1, p_kind, p_status, 'migration', p_local_date, p_start_minutes, p_service_duration_minutes, p_buffer_minutes, p_service_id, p_variant_id, p_service_name_snapshot, p_variant_name_snapshot, p_price_cents_snapshot, p_currency_snapshot, p_client_name, p_client_email, p_client_phone, p_client_note, p_internal_note, null, p_legacy_firestore_id, p_timestamp_provenance, p_imported_at, p_cancelled_at, p_cancelled_by, p_cancellation_reason, p_version, p_created_at, p_updated_at );
insert into gioia_private.domain_change_log ( aggregate_kind, aggregate_id, aggregate_version, change_kind, source, migration_run_id, changed_fields ) values ( 'schedule_entry', p_target_id, p_version, case when p_kind = 'block' then 'block' else 'create' end, 'migration', p_run_id, array[ 'kind','status','source','local_date','start_minutes', 'service_duration_minutes','buffer_minutes','legacy_firestore_id', 'timestamp_provenance' ]::text[] );
return true;
end;
$$;
create function gioia_private.apply_legacy_vacation_import( p_run_id uuid, p_source_record_id text, p_source_record_sha256 bytea, p_target_record_sha256 bytea, p_target_id uuid, p_legacy_firestore_id text, p_start_date date, p_end_date date, p_status text, p_reason text, p_cancelled_at timestamptz, p_timestamp_provenance text, p_imported_at timestamptz, p_created_at timestamptz, p_updated_at timestamptz, p_version integer ) returns boolean language plpgsql volatile security definer set search_path = '' as $$ declare v_mode text;
begin if p_legacy_firestore_id is distinct from p_source_record_id then raise sqlstate 'PT422' using message = 'MIGRATION_LEGACY_ID_MISMATCH';
end if;
v_mode := gioia_private.prepare_legacy_migration_import_record( p_run_id, 'vacations', p_source_record_id, p_source_record_sha256, 'imported', 'vacation', p_target_id, p_target_record_sha256 );
if v_mode <> 'new' then if not exists ( select 1 from gioia_private.vacations as vacation where vacation.id = p_target_id and vacation.legacy_firestore_id = p_source_record_id and vacation.source = 'migration' ) then raise sqlstate 'PT409' using message = 'MIGRATION_TARGET_MISSING';
end if;
return false;
end if;
insert into gioia_private.vacations ( id, schema_version, start_date, end_date, status, reason, source, created_by, legacy_firestore_id, timestamp_provenance, imported_at, cancelled_at, cancelled_by, version, created_at, updated_at ) values ( p_target_id, 1, p_start_date, p_end_date, p_status, p_reason, 'migration', null, p_legacy_firestore_id, p_timestamp_provenance, p_imported_at, p_cancelled_at, null, p_version, p_created_at, p_updated_at );
insert into gioia_private.domain_change_log ( aggregate_kind, aggregate_id, aggregate_version, change_kind, source, migration_run_id, changed_fields ) values ( 'vacation', p_target_id, p_version, 'create', 'migration', p_run_id, array[ 'start_date','end_date','status','source','legacy_firestore_id', 'timestamp_provenance' ]::text[] );
return true;
end;
$$;
create function gioia_private.apply_legacy_subscriber_import( p_run_id uuid, p_source_record_id text, p_source_record_sha256 bytea, p_target_record_sha256 bytea, p_target_id uuid, p_legacy_firestore_id text, p_email text, p_status text, p_consent_at timestamptz, p_consent_source text, p_consent_policy_version text, p_confirmed_at timestamptz, p_unsubscribed_at timestamptz, p_timestamp_provenance text, p_imported_at timestamptz, p_created_at timestamptz, p_updated_at timestamptz, p_version integer ) returns boolean language plpgsql volatile security definer set search_path = '' as $$ declare v_mode text;
begin if p_legacy_firestore_id is distinct from p_source_record_id then raise sqlstate 'PT422' using message = 'MIGRATION_LEGACY_ID_MISMATCH';
end if;
v_mode := gioia_private.prepare_legacy_migration_import_record( p_run_id, 'newsletter_subscribers', p_source_record_id, p_source_record_sha256, 'imported', 'subscriber', p_target_id, p_target_record_sha256 );
if v_mode <> 'new' then if not exists ( select 1 from gioia_private.newsletter_subscribers as subscriber where subscriber.id = p_target_id and subscriber.legacy_firestore_id = p_source_record_id and subscriber.source = 'migration' ) then raise sqlstate 'PT409' using message = 'MIGRATION_TARGET_MISSING';
end if;
return false;
end if;
insert into gioia_private.newsletter_subscribers ( id, schema_version, email, status, source, consent_at, consent_source, consent_policy_version, confirmed_at, unsubscribed_at, legacy_firestore_id, timestamp_provenance, imported_at, version, created_at, updated_at ) values ( p_target_id, 1, p_email, p_status, 'migration', p_consent_at, p_consent_source, p_consent_policy_version, p_confirmed_at, p_unsubscribed_at, p_legacy_firestore_id, p_timestamp_provenance, p_imported_at, p_version, p_created_at, p_updated_at );
insert into gioia_private.domain_change_log ( aggregate_kind, aggregate_id, aggregate_version, change_kind, source, migration_run_id, changed_fields ) values ( 'subscriber', p_target_id, p_version, 'subscribe', 'migration', p_run_id, array[ 'email','status','source','legacy_firestore_id','timestamp_provenance' ]::text[] );
return true;
end;
$$;
reset role;
set local role gioia_migrator;
create function gioia_private.apply_legacy_quarantine_import( p_run_id uuid, p_source_collection text, p_source_record_id text, p_source_record_sha256 bytea, p_reason_code text, p_field_codes text[] ) returns boolean language plpgsql volatile security definer set search_path = '' as $$ declare v_mode text;
begin if p_reason_code is null or p_reason_code !~ '^[A-Z][A-Z0-9_]{1,63}$' or p_field_codes is null or pg_catalog.cardinality(p_field_codes) > 50 or pg_catalog.array_position(p_field_codes, null::text) is not null or ( pg_catalog.cardinality(p_field_codes) > 0 and pg_catalog.array_to_string(p_field_codes, ',') !~ '^[A-Z][A-Z0-9_]{1,63}(,[A-Z][A-Z0-9_]{1,63})*$' ) then raise sqlstate 'PT422' using message = 'MIGRATION_QUARANTINE_INVALID';
end if;
v_mode := gioia_private.prepare_legacy_migration_import_record( p_run_id, p_source_collection, p_source_record_id, p_source_record_sha256, 'quarantined', null, null, null );
if v_mode = 'same_run_replay' then return false;
end if;
insert into gioia_private.migration_quarantine ( run_id, source_collection, source_record_id, reason_code, field_codes ) values ( p_run_id, p_source_collection, p_source_record_id, p_reason_code, p_field_codes );
return v_mode = 'new';
end;
$$;
create function gioia_private.complete_legacy_migration_import(p_run_id uuid) returns table ( source_count integer, imported_count integer, quarantined_count integer ) language plpgsql volatile security definer set search_path = '' as $$ declare v_run gioia_private.migration_runs%rowtype;
v_source integer;
v_imported integer;
v_quarantined integer;
v_expected integer;
begin select run.* into v_run from gioia_private.migration_runs as run where run.id = p_run_id for update;
if not found or v_run.run_kind <> 'import' or v_run.dry_run or v_run.status not in ('running', 'completed') then raise sqlstate 'PT409' using message = 'MIGRATION_RUN_NOT_COMPLETABLE';
end if;
select pg_catalog.count(*)::integer, pg_catalog.count(*) filter (where disposition = 'imported')::integer, pg_catalog.count(*) filter (where disposition = 'quarantined')::integer into v_source, v_imported, v_quarantined from gioia_private.migration_records as record where record.run_id = p_run_id;
if v_run.status = 'running' then v_expected := (v_run.counts ->> 'expectedSource')::integer;
if v_expected is null or v_expected not between 1 and 100 or v_source <> v_expected or v_imported + v_quarantined <> v_source then raise sqlstate 'PT409' using message = 'MIGRATION_COUNTS_MISMATCH';
end if;
update gioia_private.migration_runs set status = 'completed', completed_at = pg_catalog.statement_timestamp(), counts = pg_catalog.jsonb_build_object( 'source', v_source, 'imported', v_imported, 'quarantined', v_quarantined ) where id = p_run_id;
elsif v_run.counts <> pg_catalog.jsonb_build_object( 'source', v_source, 'imported', v_imported, 'quarantined', v_quarantined ) then raise sqlstate 'PT409' using message = 'MIGRATION_COUNTS_MISMATCH';
end if;
return query select v_source, v_imported, v_quarantined;
end;
$$;
reset role;
revoke create on schema gioia_private from gioia_mutator;
revoke create on schema gioia_private from gioia_migrator;
revoke all on function gioia_private.prepare_legacy_migration_import_record( uuid,text,text,bytea,text,text,uuid,bytea ) from public, anon, authenticated, service_role, app_runtime;
grant execute on function gioia_private.prepare_legacy_migration_import_record( uuid,text,text,bytea,text,text,uuid,bytea ) to gioia_mutator;
revoke all on function gioia_private.begin_legacy_migration_import( uuid,text,bytea,smallint ) from public, anon, authenticated, service_role, app_runtime;
revoke all on function gioia_private.apply_legacy_schedule_import( uuid,text,bytea,bytea,uuid,text,text,text,date,smallint,smallint,smallint, text,text,text,text,integer,text,text,text,text,text,text,text,timestamptz, text,text,timestamptz,timestamptz,timestamptz,integer ) from public, anon, authenticated, service_role, app_runtime;
revoke all on function gioia_private.apply_legacy_vacation_import( uuid,text,bytea,bytea,uuid,text,date,date,text,text,timestamptz,text, timestamptz,timestamptz,timestamptz,integer ) from public, anon, authenticated, service_role, app_runtime;
revoke all on function gioia_private.apply_legacy_subscriber_import( uuid,text,bytea,bytea,uuid,text,text,text,timestamptz,text,text, timestamptz,timestamptz,text,timestamptz,timestamptz,timestamptz,integer ) from public, anon, authenticated, service_role, app_runtime;
revoke all on function gioia_private.apply_legacy_quarantine_import( uuid,text,text,bytea,text,text[] ) from public, anon, authenticated, service_role, app_runtime;
revoke all on function gioia_private.complete_legacy_migration_import(uuid) from public, anon, authenticated, service_role, app_runtime;
grant execute on function gioia_private.begin_legacy_migration_import( uuid,text,bytea,smallint ) to gioia_migrator;
grant execute on function gioia_private.apply_legacy_schedule_import( uuid,text,bytea,bytea,uuid,text,text,text,date,smallint,smallint,smallint, text,text,text,text,integer,text,text,text,text,text,text,text,timestamptz, text,text,timestamptz,timestamptz,timestamptz,integer ) to gioia_migrator;
grant execute on function gioia_private.apply_legacy_vacation_import( uuid,text,bytea,bytea,uuid,text,date,date,text,text,timestamptz,text, timestamptz,timestamptz,timestamptz,integer ) to gioia_migrator;
grant execute on function gioia_private.apply_legacy_subscriber_import( uuid,text,bytea,bytea,uuid,text,text,text,timestamptz,text,text, timestamptz,timestamptz,text,timestamptz,timestamptz,timestamptz,integer ) to gioia_migrator;
grant execute on function gioia_private.apply_legacy_quarantine_import( uuid,text,text,bytea,text,text[] ) to gioia_migrator;
grant execute on function gioia_private.complete_legacy_migration_import(uuid) to gioia_migrator;
revoke insert, update, delete on table gioia_private.schedule_entries, gioia_private.vacations, gioia_private.newsletter_subscribers from gioia_migrator;
revoke gioia_mutator from postgres;
revoke gioia_migrator from postgres;
commit;
